Django/wishlist/apps/wishlist_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [ 
   url(r'^$', views.index, name = 'index'),
   url(r'^create$', views.create, name = 'create'),
   url(r'^homepage$', views.homepage, name = 'homepage'), #views.py needs to have a matching "def homepage"
   url(r'^login$', views.login, name = 'login'),
   url(r'^logout$', views.logout, name = 'logout'),
   url(r'^new_wish$', views.new_wish, name = 'new_wish'),
   url(r'^add_wish_page$', views.add_wish_page, name = 'add_wish_page'),
   url(r'^item_profile_page/(?P<item_id>\d+)$', views.item_profile_page, name = 'item_profile_page'),
   url(r'^add_to_list/(?P<item_id>\d+)$', views.add_to_list, name = 'add_to_list'),
   url(r'^remove/(?P<item_id>\d+)$', views.remove, name = 'remove'),


#    /(?P<id>\d+)


]

Django/wishlist/wishlist/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.wishlist_app.urls', namespace='wishlist_app')),
]

Django/wishlist/apps/wishlist_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')
# Create your models here.

class UserManager(models.Manager):
    def reg_validator(self, postData):
        errors = {}
        if len(postData["name"]) < 3:
            errors["name"] = "first name should be more than 3 characters"           
        if len(postData["username"]) < 3:
            errors["username"] = "username name should be more than 3 characters"
        if len(postData['password']) < 8:
            errors["password"] = "password should be more than 8 character"
        # if not re.match(EMAIL_REGEX, postData['emailreg']):
        #     errors["emailreg"] = ("invalid email")
        if not re.match(NAME_REGEX, postData['name']):
            errors["name"] = ("invalid first name")
        if not re.match(NAME_REGEX, postData['username']):
            errors["username"] = ("invalid username")
        if User.objects.filter(username = postData ['username']).exists():
            errors ['username'] = "username already registered"
        
        return errors
        try:
            User.objects.get(email = postData['emailreg'])
            errors['emailreg'] = "The email is already taken"
        except:
            pass
        return
    def log_validator(self, postData): 
        errors = {}
        try: 
            user = User.objects.get(username=postData['username']) # models needs to be =postData, no request, because passing in variable of postdata
        except:
            errors['nonexistant'] = "user does not exist"               
        if len(postData['password']) < 8:
            errors["length"] = "password name should be more than 8 character"            
        if len(User.objects.filter(username = postData['username'])) > 0:
            correct_user = User.objects.filter(username = postData["username"])[0]
            # need to make [0] since a list needs a starting point            
        if errors:
            return errors
        hash1 = bcrypt.checkpw(postData['password'].encode('utf8'), user.password.encode('utf8'))
        if hash1 == False:
            errors ['password'] = "Wrong password"
        return errors    
        return

class ItemManager(models.Manager):
    def item_validator(self, postData):
        errors = {}
        if len(postData["name"]) < 3:
            errors["name"] = "item name should be more than 3 characters"
        if len(postData["name"]) == 0:
            errors["name"] = "item name cannot be blank"
        
        return errors    
        return

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    createdat = models.DateTimeField(auto_now_add = True)
    updatedat = models.DateTimeField(auto_now = True)
    hired = models.DateField(null=True)    
    objects = UserManager()
#class name needs to be capital

class Item(models.Model):
    name = models.CharField(max_length=255)
    wished_by = models.ManyToManyField(User, related_name = "most_wanted" )
    created_by = models.ForeignKey(User, related_name = "most_created")
    createdat = models.DateTimeField(auto_now_add = True)
    updatedat = models.DateTimeField(auto_now = True)
    objects = ItemManager()


# item.createdby returns a "user" need to filter further . name

Django/wishlist/apps/wishlist_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from time import gmtime, strftime
from django.utils.crypto import get_random_string
from models import User, Item
import bcrypt

# Create your views here.


# def index(request):
#    response = "Hello, I am your first request!"
#    return HttpResponse(response)
def index(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'index.html', context)

def create(request):
    errors = User.objects.reg_validator(request.POST)
    if len (errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')

    else:
        name = request.POST['name']
        username = request.POST['username']
        
        password = request.POST['password']
        hired = request.POST['hired']
        confirm = request.POST['confirm']
        hashed = bcrypt.hashpw(password.encode('utf8'), bcrypt.gensalt())           
        person = User.objects.create(name=name, password=hashed, username=username, hired=hired)#need to pass in hashed password into database alias=alias,
        request.session["id"] = person.id
        person.save()
        print "registrant was created"
        return redirect("/homepage") # do not render to POST, could get lost in loop
        #now redirct to route that handles sucess page 
        #return redirect('/')

def login(request):
    errors = User.objects.log_validator(request.POST)
    user = User.objects.get(username=request.POST['username'])
    if len (errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect( "/")
    else:
        bcrypt.checkpw('password'.encode('utf8'), user.password.encode('utf8'))
        request.session['id'] = user.id

        return redirect( "/homepage")

def homepage(request): #request is default parameter
    user = User.objects.get(id=request.session['id'])
    users = User.objects.all()
    items = Item.objects.filter(wished_by=user)
    # print Item.objects.filter().wished_by    
    otherwishlist = Item.objects.exclude(wished_by=user)
    # mylist = User.most_wanted.wished_by(id=user.id)
    #take whole object and filter on html 
    #make seperate context items to easily loop through items
    context = {
        'user': User.objects.get(id=request.session['id']),
        'otherwishlist' : otherwishlist,
        'items' : items,
        # 'mylist' : mylist,

    }
    
    return render (request, "homepage.html", context) 

#handles form sub
#save items here
def new_wish(request):
#default process is to grab the current user id first, when creating item in database
#next the objects foreign key, in this case the name, needs to be created. with each parameter passed on 
    
    user = User.objects.get(id=request.session['id'])
    name = Item.objects.create(name=request.POST["item_name"], created_by=user)
    # IntegrityError: wishlist_app_item.created_by_id may not be NULL
    #had name first, but threw above error. Need user id for foreign key created_by
   


    # response = "Hello, I am your wishlist page!"
    # return HttpResponse(response)
    return redirect('/homepage')

#serves up page
#load items here
def add_wish_page(request):
    # items = Item.objects.all()
    # print items
    # context = {
    #     'items': items
    #     # Item.objects.get(id=request.session['id'])
    # }
    return render(request, 'new_wish.html')
# , context)

def item_profile_page(request, item_id):
    # user = User.objects.get(id=request.session['id'])
    
    current_items = Item.objects.get(id=item_id)
    this_item = current_items.wished_by.all()
    # print current_items.wished_by.f
    # print users_who_liked
    # users_who_liked = User.objects.filter(most_wanted=item)

    # for x in users_who_liked:
    #     print x
    context = {
        # 'item': item,
        # 'user' : user, 
        'item' : Item.objects.get(id=item_id), 
        'this_item' : this_item,
              
    }
    return render(request, 'item_profile.html', context)

def add_to_list(request, item_id):
    user = User.objects.get(id=request.session['id'])
    item = Item.objects.get(id=item_id)
    item.wished_by.add(user)
    item.save()

    return redirect('/homepage')

def also_added_to_wishlist(request, item_id):
    user = User.objects.get(id=request.session['id'])
    item = Item.objects.get(id=item_id)
    wanted_by = Item.objects.all()

    #when doing reverse lookup using related name need to put
    #related name after user class
    # also_wished = Item.wished_by.filter(id=item_id)

    # this_publisher.books.add(this_book)
    
    return redirect ('/')

def remove(request, item_id):
    user = User.objects.get(id=request.session['id'])
    item = Item.objects.get(id=item_id)
    item.wished_by.remove(user)
    item.save()

    return redirect('/homepage')

def logout(request):
    request.session.clear()
    return redirect('/')

Django/wishlist/apps/wishlist_app/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Wishlist</title>
</head>
<body>
        <h1>Success, Welcome {{ users.firstname}}</h1>
        <div class="logout">
            <form action="logout" method="POST">
                {% csrf_token %}
                <input type="submit" name="logout" value="logout">
            </form>
           Successfully registered or logged in!!  
        </div>
        <!-- what is the regular way to do below -->
        <div>
            {% if items %}
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added by</th>
                    <th>Date added</th>
                    <th>Action</th>
                </tr>
                {% for Item in items %}            
                <tr>
                    <td><a href="{% url 'wishlist_app:item_profile_page' Item.id %}">{{Item.name}}</a></td>
                    <!-- item.created_by only returns whole object. need to whittle down further -->
                    <td>{{Item.created_by.name}}</td>
                    <td>{{Item.createdat}}</td>                                   
                    
                    <td>{% if items %}
                        <a href="{% url 'wishlist_app:remove' Item.id %}" >remove from wishlist</a>
                        {% else %}
                        <!-- <p> <a href=>erase from database</a></p>                         -->
                    </td>{% endif %}
                </tr>
                {% endfor %}
                {% else %}<p> You have no wishlist items!</p>
            {% endif %}            
            </table>   

        </div>
        <div>
            {% if otherwishlist %}
            <table>
                <tr>
                    <th>Item</th>
                    <th>Added by</th>
                    <th>Date added</th>
                    <th>Action</th>
                </tr>
                {% for others in otherwishlist %}            
                <tr>
                    <td><a href="{% url 'wishlist_app:item_profile_page' others.id %}">{{others.name}}</a></td>
                    <!-- item.created_by only returns whole object. need to whittle down further -->
                    <td>{{others.created_by.name}}</td>
                    <td>{{others.createdat}}</td>                                   
                    
                    <td>{% if others %}
                        <a href="{% url 'wishlist_app:add_to_list' others.id %}" >add to wishlist</a>
                        {% else %}
                        <!-- <p> <a href=>erase from database</a></p>                         -->
                    </td>{% endif %}
                </tr>
                {% endfor %}
                {% else %}
            {% endif %}            
            </table>   

        </div>    
        <a href= "{% url 'wishlist_app:add_wish_page' %}">Add merchandise</a>
</body>
</html>

Django/wishlist/apps/wishlist_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Wishlist</title>
</head>
<body>
    <h1> Welcome! </h1>
    <h2>Registration</h2> 
    <div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    
    <div>
        <!-- with namespace and url you don't need to type in ........have to use *brace brace percent whatever precent brace brace to use -->
        <form action= "{% url 'wishlist_app:create' %}" method="POST"> <!--format is as shown "<insert brace>% url 'users:logout' %<insert brace>"           big url : little url n due to namespace convention-->
            {% csrf_token %}
            name:<br>
            <!-- input means form -->
            <input type="text" name="name" placeholder="name"> <!-- need? value=""-->
            <br>
            username:<br>
            <input type="text" name="username" placeholder="username">
            <br>            
            Password:<br>
            <input type="password" name="password" placeholder="Password">
            <br>
            <p>Password should be at least 8 characters</p>
            Password Confirm:<br>
            <input type="password" name="confirm" placeholder="Pass Confirm">
            Date Hired:<br>
            <input type="date" name="hired" placeholder=" mm/dd/yyyy">
            <input type="submit" value="Register">
        </form>    
    </div>
    <h2>Login<h2>
        <div>       
            <form action="{% url 'wishlist_app:login' %}" method="POST">
                {% csrf_token %} 
                username:<br>
                <input type="text" name="username" placeholder="username">
                <br>
                Password:<br>
                <input type="password" name="password" placeholder="Password">
                <br>
                
                <input type="submit" value="Login">
            </form>
        </div>
</body>
</html>

Django/wishlist/apps/wishlist_app/templates/item_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Item Profile</title>
</head>
<body>
    <div>
        <h1><td>{{item.name}}</td></h1>
        <a href= "{% url 'wishlist_app:logout' %}">Logout</a>
        <a href= "{% url 'wishlist_app:homepage' %}">Home</a>
    </div>
    <div>
        <h2> Users who added this product/item under their wish list:</h2>

        <div>
            
            <ul>
                {% for item in this_item %}
                <li >
                        {{item.name}}
                    <!-- {{ message.user }} -->
                </li>
                {% endfor %}
            </ul>
            
        </div>
        

    </div>
</body>
</html>U

Django/wishlist/apps/wishlist_app/templates/new_wish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add to Wishes</title>
</head>
<body>
    <div>
        <h1>Create a New Wish List Item</h1>
        <a href= "{% url 'wishlist_app:logout' %}">Logout</a>
        <a href= "{% url 'wishlist_app:homepage' %}">Home</a>
    </div>
    <div>
        <form action= "{% url 'wishlist_app:new_wish' %}" method="POST"> <!--format is as shown "<insert brace>% url 'users:logout' %<insert brace>"           big url : little url n due to namespace convention-->
                {% csrf_token %}
                Item/Product:<br>                
                <input type="text" name="item_name"> 
                <br>
                <input type="submit" value="add">
        </form> 
    </div>
</body>
</html>