Django/pythonbeltexam/apps/pythonbelt_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [     
    #name of <form acton= xxx> goes in first place. ( after r'^ ). 
    url(r'^$', views.index, name = 'index'),
    #everytime a new user created, they are by default given an id
    # using this we can change the route be dynamic as below
    url(r'^create$', views.create, name = "create"), #in views need to have a route with the same name
    url(r'^homepage$', views.homepage, name = 'homepage'), # routing, now routing to 'whatever' definition. make a new 'whatever' def on views page
    url(r'^login$', views.login, name = 'login'),
    url(r'^logout$', views.logout, name = 'logout'),
    url(r'^add/(?P<id>\d+)$', views.add, name = 'add'),
    url(r'^erase/(?P<id>\d+)$', views.erase, name = 'erase'),
    url(r'^profile/(?P<id>\d+)$', views.profile, name = 'profile')
]

Django/pythonbeltexam/pythonbeltexam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [ 
    url(r'^', include('apps.pythonbelt_app.urls', namespace='pythonbelt_app'))
]

Django/pythonbeltexam/apps/pythonbelt_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')

# Create your models here.

class BlogManager(models.Manager):
    def reg_validator(self, postData):
        errors = {}
        if len(postData["name"]) < 3:
            errors["name"] = "first name should be more than 1 character"
            # was name instead of first name length
        if len(postData["username"]) < 3:
            errors["username"] = "last name should be more than 1 character"
        if len(postData['password']) < 8:
            errors["password"] = "password should be more than 8 character"
        
        if not re.match(NAME_REGEX, postData['name']):
            errors["name"] = ("invalid first name")
        if not re.match(NAME_REGEX, postData['username']):
            errors["username"] = ("invalid username name")
        # if User.objects.filter(email = postData ['emailreg']).exists():
        #     errors ['emailreg'] = "email already registered"
        if len(postData['username']) < 2:
            errors["username"] = "username needs to be longer than 2 char"
        if (User.objects.filter(username = postData['username']).exists()):
            errors['username'] = "username taken already"
        if postData['bday'] == None:
            errors['bday'] = "Invalid DOB"
        
        
        return errors
        try:
            User.objects.get(email = postData['username'])
            errors['username'] = "The username is already taken"
        except:
            pass
        return
    def log_validator(self, postData): #need to finish
        errors = {}
        user = User.objects.get(username=postData['username']) # models needs to be =postData, no request, because passing in variable of postdata
        #hashcheck = None python not needed?
        if len(postData['password']) < 8:
            errors["length"] = "password name should be more than 8 character"
            # was name instead of first name length
        if len(User.objects.filter(username = postData['username'])) < 0:
            correct_user = User.objects.filter(username = postData["username"])
        hash1 = bcrypt.checkpw(postData['password'].encode('utf8'), user.password.encode('utf8'))
        if hash1 == False:
            errors ['password'] = "Wrong password"
           # errors["email"] = "Blog name should be more than 1 character"
        # if type
        # if len(postData['desc']) < 10:
            # errors["desc"] = "Blog desc should be more than 10 characters"
        return errors

class RelationManager(models.Manager):
    def friend_validator(self, id1, id2):
        errors = {}
        if (id1 == id2):
            errors["friend1_id"] = "Friendship requires two different people"
        elif (User.objects.filter(friend1_id = int(id1), friend2_id = int(id2)).exists()):
            errors["friend1_id"] = "You two aren't strangers"
        # elif (User.objects.filter)
        return errors

   

class User(models.Model):
    #everything...... variables are case sensitive
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    # email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    wish = models.ManyToManyField("self", blank=True, related_name="friended_me")
    createdat = models.DateTimeField(auto_now_add = True)
    updatedat = models.DateTimeField(auto_now = True)
    hired = models.DateField(null=True)
    # Format='%m/%d/%y' not needed in datefield ( here ) above
    # objects = RelationManager()
    objects = BlogManager()

class Wish(models.Model):
    name = models.CharField(max_length=255)
    wanted = models.ForeignKey(User, related_name="wanted_by") 




   

Django/pythonbeltexam/apps/pythonbelt_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect, reverse
from django.contrib import messages
from time import gmtime, strftime
from django.utils.crypto import get_random_string
from models import User
import bcrypt
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    response = "Hello, I am your first request!"
    users = User.objects.all()
    context = {
        'users': users
    }
  # return HttpResponse(response)
    return render(request, 'index.html', context)

def create(request):
    errors = User.objects.reg_validator(request.POST)
    if len (errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect('/')

    else:
        name = request.POST['name']
        username = request.POST['username']
        # email = request.POST['emailreg']
        password = request.POST['password']
        hired = request.POST['bday']
        confirm = request.POST['confirm']
        hashed = bcrypt.hashpw(password.encode('utf8'), bcrypt.gensalt())           
        person = User.objects.create(name=name, username=username, password=hashed, hired=hired)#need to pass in hashed password into database alias=alias,
        request.session["id"] = person.id
        person.save()
        print "registrant was created"
        return redirect("/homepage") # do not render to POST, could get lost in loop
        #now redirct to route that handles sucess page 
        #return redirect('/')

def login(request):
    errors = User.objects.log_validator(request.POST)
    user = User.objects.get(email=request.POST['emaillog'])
    if len (errors):
        for tag, error in errors.iteritems():
            messages.error(request, error, extra_tags=tag)
        return redirect( "/")
    else:
        bcrypt.checkpw('password'.encode('utf8'), user.password.encode('utf8'))
        request.session['id'] = user.id

        return redirect( "/homepage")
        # changed to redirect because 
    #errors = Users.objects.login_validator(request.POST)
    #password = request.post['password']

def homepage(request): #request is default parameter
    current_user = User.objects.get(id=request.session['id'])#current_user will be used in homepage welcoming
    users = User.objects.all()
    # wish = User.objects.exclude(wish=current_user).exclude(id=current_user.id)
    context = {
        # 'wish' : User.objects.exclude(wish=current_user).exclude(id=current_user.id),
        'wish' :current_user.wish.all(),
        'current_user' : current_user,
    }
     #'users': User.objects.get(id=request.session['id'])
    return render (request, "homepage.html", context) 

def logout(request):
    request.session.clear()
    return redirect('/')

def profile(request, id):
    
    #id=id<---- second id needs to match parameter req'd by function
     #reverse is for traversing through things
     #something in context taking in not showing
    context = {
        'friend' : User.objects.get(id=id)#whatever in quotes gets sent to html file.
    }
    response = "Hello, I'm creeping on your profile!"
    return render(request, 'friendsinfo.html', context)


def add(request, id):
    friend = User.objects.get(id=id)
    #when referring to the current user who is logged in, use below
    current_user = User.objects.get(id=request.session['id'])
    #create a relation between current user and friend
    current_user.friend.add(friend)
    #not saved until
    current_user.save()
    #now create relation between friend and user
    friend.friend.add(current_user)
    friend.save()
    print friend.name
    response = "Hello, I am your new friend!"
    #try to send back to page we are already at, so below
    print current_user.friend
    context = {
        'users' : User.objects.exclude(friend=current_user).exclude(id=current_user.id),
        'friends' :current_user.friend.all(),
        'current_user' : current_user,
    }
    # return render(request, 'homepage.html', context)
    return redirect('/add', context)
   


 
def erase(request, id):
    stranger = User.objects.get(id=id)
    current_user = User.objects.get(id=request.session['id'])
    current_user.friend.remove(stranger)
    current_user.save()
    stranger.friend.remove(current_user)
    stranger.save()
    context = {
        'friends' : User.objects.all()
    }
    return redirect('/homepage', context)
#
    

Django/pythonbeltexam/apps/pythonbelt_app/templates/friendsinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Friends Info</title>
</head>
<body>
    <div>
        <h3><a href ="{% url 'pythonbelt_app:homepage' %}">Home</a></h3>
        <h3><a href ="{% url 'pythonbelt_app:logout' %}">Logout</a></h3>
    </div>
<!-- whatever gets passed in context in quotes is what is called below. this case "friend" was made the string to call -->
    <h1>{{ friend.firstname }} Profile</h1>

    <div>
        <p><strong>First Name and Alias:</strong> {{ friend.name }} {{ friend.username }}</p><br>
        <!-- <p></p><strong>Email Address:</strong> {{ friend.email }}</p><br> -->
    </div>
</body>
</html> 

Django/pythonbeltexam/apps/pythonbelt_app/templates/homepage.1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Friends App</title>
</head>
<body>
    <div>
        <h1>Hello, {{ current_user.firstname}}</h1> <a href="{% url 'pythonbelt_app:logout' %}">Logout</a>
    </div>
    {% if friends %}
    <h2>Here is the list of your friends</h2>
    <div>
        <table>
            <tr>
                <th>Alias</th>
                <th>Actions</th>                                   
            </tr>            
            {% for friend in friends %}
            <tr>
                <td>{{friend.username}}</td>                                   
                <td> 
                    <a action=profile method="GET" href="{% url 'pythonbelt_app:profile' friend.id %}">View Profile</a>
                    <a action=remove method="POST" href="{% url 'pythonbelt_app:erase' friend.id %}">erase as a Friend</a>                        
                </td>
            </tr>
            {% endfor %}
    {% else %}<p> You have no wishlist yet! </p>{% endif %}            
        </table>        
    </div>
    <div><h2>Other Users not on your friends list</h2>
            <table>
                <thead>
                    <th>Alias</th>
                    <th>Actions</th>                                   
                </thead>         
                <!-- need loop to cycle through db to list data  -->
               {% for user in users %} 
                <tr>
                    <!-- below identifies data to pull from db. calls user object and pulls attribute of firstname -->
                    <td><a href="{% url 'pythonbelt_app:profile' user.id %}">{{ user.alias }} </a></td>
                    <td><a href="{% url 'pythonbelt_app:add' user.id %}">Add Friend</a></td>
                    <!-- can't do this: why? <td><input type="submit" name="add" value="add as friend"></td>
 -->
                </tr>
                <!-- <div class="add">
                    <form action="add" method="POST">
                        {% csrf_token %}
                        
                    </form>
                
                </div> -->
                {% endfor %}
            </table>

    </div>
        

  

</body>
</html> 




    <!-- <div class="logout">
        <form action="logout" method="POST">
            {% csrf_token %}
            <input type="submit" name="logout" value="logout">
        </form>
       Successfully registered or logged in!!  
    </div> -->

Django/pythonbeltexam/apps/pythonbelt_app/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Friends App</title>
</head>
<body>
    <div>
        <h1>Hello, {{ current_user.name}}</h1> <a href="{% url 'pythonbelt_app:logout' %}">Logout</a>
    </div>
    
    <div><h2>Your wish list</h2>
            <table>
                <thead>
                    <th>Item</th>
                    <th>Added by</th>
                    <th>Date Added </th>  
                    <th>Action</th>                                     
                </thead>                
               {% for user in users %} 
                <tr>
                    <!-- <td><a href="{% url 'pythonbelt_app:profile' user.id %}">{{ user.username }} </a></td>
                    <td><a href="{% url 'pythonbelt_app:add' user.id %}">Add </a></td>
                    <td><a href="{% url 'pythonbelt_app:add' user.id %}">Add </a></td>
                    <td><a href="{% url 'pythonbelt_app:add' user.id %}">Add </a></td> -->
                </tr>
           
                {% endfor %}
            </table>
            <button><a href="{% url 'pythonbelt_app:add' user.id %}">Add A New Item</a></button>
    </div>
</body>
</html> 

Django/pythonbeltexam/apps/pythonbelt_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login & Registration</title>
</head>
<body>
    <h1> Welcome! </h1>
    <h2>Registration</h2> 
    <div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        <!-- with namespace and url you don't need to type in ........have to use *brace brace percent whatever precent brace brace to use -->
        <form action= "{% url 'pythonbelt_app:create' %}" method="POST"> <!--format is as shown "<insert brace>% url 'users:logout' %<insert brace>"           big url : little url n due to namespace convention-->
            {% csrf_token %}
             name:<br>
            <!-- input means form -->
            <input type="text" name="name" placeholder=" Name"> <!-- need? value=""-->
            <br>
            username:<br>
            <input type="text" name="username" placeholder="username">
            <br>
            
            Password:<br>
            <input type="password" name="password" placeholder="Password">
            <br>
            <p>Password should be at least 8 characters</p>
            Password Confirm:<br>
            <input type="password" name="confirm" placeholder="Pass Confirm">
            Hired:<br>
            <input type="date" name="bday" placeholder=" mm/dd/yyyy">
            <input type="submit" value="Register">
        </form>    
    </div>
    <h2>Login<h2>
        <div>       
            <form action="{% url 'pythonbelt_app:login' %}" method="POST">
                {% csrf_token %} 
                username:<br>
                <input type="text" name="emaillog" placeholder="Email">
                <br>
                Password:<br>
                <input type="password" name="password" placeholder="Password">
                <br>
                
                <input type="submit" value="Login">
            </form>
        </div>
</body>
</html>

Django/pythonbeltexam/apps/pythonbelt_app/templates/new_wish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New Wish</title>
</head>
<body>
    <div>
        <h1>Create a New Wish List item</h1> <a href="{% url 'pythonbelt_app:logout' %}">Logout</a>
    </div>
    
    <div><h2>Item/Product</h2>
        <form action= "{% url 'pythonbelt_app:add' user.id %}" method="POST"> 
            {% csrf_token %}
            Item Product:<br>
            <input type="text" name="newwish"> 
            <br>
            <input type="submit" value="newwish">
        </form> 
    </div>

</body>
</html> 

Django/pythonbeltexam/apps/pythonbelt_app/templates/strangersinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Stranger Info</title>
</head>
<body>
    <div>
        <h3><a href = 'homepage.html'>Home</a></h3>
        <h3><a href = 'index.html'>Logout</a></h3>
    </div>

    <h1>{{ user.firstname }}Profile</h1>

    <div>
        <p><strong>Full Name:</strong> {{ user.first_name }}{{ user.last_name }}</p><br>
        <p></p><strong>Email Address:</strong> {{ user.email }}</p><br>
    </div>
</body>
</html> 