Django/sunday_test_project/apps/sunday_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views



urlpatterns = [ 
   url(r'^$', views.index, name = 'index'),
   url(r'^register$', views.register, name = 'register'),
   url(r'^login$', views.login, name = 'login'),
   url(r'^logout$', views.logout, name = 'logout'),
   url(r'^homepage$', views.homepage, name = 'homepage'), #views.py needs to have a matching "def homepage"
   url(r'^create$', views.create, name = 'create'),
   url(r'^collect_data$', views.collect_data, name = 'collect_data'),
   url(r'^trip_profile/(?P<trip_id>\d+)$', views.trip_profile, name = 'trip_profile'),
   url(r'^join_trip/(?P<trip_id>\d+)$', views.join_trip, name = 'join_trip'),
      
]

Django/sunday_test_project/sunday_test_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [ 
    url(r'^', include('apps.sunday_test.urls', namespace='sunday_test_project'))
]

Django/sunday_test_project/apps/sunday_test/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')



# Create your models here.
class UserManager(models.Manager):
    def reg_validator(self, postData):
        errors = []
        # Length of inputs--------------
        if len(postData["name"]) < 3:
            errors.append("first name should be more than 3 characters")
        # uncomment below if using last name and comment out alias postData
        # if len(postData["last_name"]) < 3:
        #     errors.append["last_name"] = "last name should be more than 3 characters"            
        if len(postData["alias"]) < 3:
            errors.append("alias name should be more than 3 characters")        
        if len(postData['password']) < 8:
            errors.append("password should be more than 8 character")

        #  If inputs are valid characters
        if not re.match(EMAIL_REGEX, postData['emailreg']):
            errors.append("invalid email")
        if not re.match(NAME_REGEX, postData['name']):
            errors.append("invalid first name")
        if not re.match(NAME_REGEX, postData['alias']):
            errors.append("invalid alias")

        # If alias already exists
        if User.objects.filter(alias = postData ['alias']).exists():
            errors.append("alias already registered")
        
        return errors
        try:
            User.objects.get(email = postData['emailreg'])
            errors.append("The email is already taken")
        except:
            pass
        return


    def log_validator(self, postData): 
        errors = []
        try: 
        # models needs to be =postData, no request, because passing in variable of postdata
            user = User.objects.get(email=postData['emaillog'])
        except:
            errors.append("user does not exist")   

        if len(postData['password']) < 8:
            errors.append("password name should be more than 8 character")            
        if len(User.objects.filter(email = postData['alias'])) > 0:
            correct_user = User.objects.filter(email = postData["alias"])[0]
            # need to make [0] since a list needs a starting point            
        if errors:
            return errors
        hash1 = bcrypt.checkpw(postData['password'].encode('utf8'), user.password.encode('utf8'))
        if hash1 == False:
            errors.append("Wrong password")
        return errors    
        return


class TripManager(models.Manager):
    def validate_trip(self, input):
        errors = []
        location = input['location']
        description = input['description']
        date_from = input['date_from']
        date_to = input['date_to']
        if not location or location.isspace():
            errors.append("Please input your location to land")
        if not description or description.isspace():
            errors.append("Please input your location description for your records")
        if not date_from:
            errors.append("select: departure date from")
        if not date_to:
            errors.append("select: trip arrival date to")


       
        today = datetime.datetime.now().strftime('%Y-%m-%d')
        if date_from < today:
                errors.append("date is in the past")
        if date_from > date_to:
                errors.append('dates are not chronological')
                
        return errors
        
        
             

class User(models.Model):    
    name = models.CharField(max_length=255)
    # username = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    email = models.CharField(max_length=255)    
    password = models.CharField(max_length=255)
    createdat = models.DateTimeField(auto_now_add = True)
    updatedat = models.DateTimeField(auto_now = True)
    bday = models.DateField(null=True)      
    objects = UserManager()
    def __repr__(self):
        return "<User object: {} {} {} {} {} {}>".format(self.id, self.name, self.alias, self.password, self.createdat, self.updatedat)
    #need above to print in terminal

class Trip(models.Model):
    location = models.CharField(max_length=55)
    description = models.TextField()
    date_from = models.DateField()
    date_to = models.DateField()
    users = models.ManyToManyField(User, related_name='trips')
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TripManager()
    def __repr__(self):
        return self.location

Django/sunday_test_project/apps/sunday_test/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from time import gmtime, strftime
from django.utils.crypto import get_random_string
from models import *
# need to import models above. for example in wishlist< User, Item >were the models. 
# then erase *
import bcrypt

# Create your views here.
def index(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'index.html', context)


def register(request):
    errors = User.objects.reg_validator(request.POST)
    if len(errors):
        for error in errors:
            messages.error(request, error)
        return redirect('/')

    else:
        name = request.POST['name']
        alias = request.POST['alias']
        email = request.POST['emailreg']                
        password = request.POST['password']
        bday = request.POST['bday']
        confirm = request.POST['confirm']
        hashed = bcrypt.hashpw(password.encode('utf8'), bcrypt.gensalt())           
        person = User.objects.create(name=name, password=hashed, email=email, alias=alias, bday=bday)#need to pass in hashed password into database alias=alias,
        request.session["user_id"] = person.id
        person.save()
        messages.success(request, "You've successfully registered")
        print "registrant was created"
        return redirect("/homepage")
        #do not render to POST, could get lost in loop
        #now redirct to route that handles success page 

def login(request):
    errors = User.objects.log_validator(request.POST)
    password = request.POST['password']
    try:
        user_login = User.objects.get(alias=request.POST['alias'])
    except Exception:
        errors.append('Email not in our database')
        for error in errors:
            messages.warning(request, error)
        return redirect('/')

    password_check = bcrypt.checkpw(password.encode(), user_login.password.encode())

    if password_check == True:
        request.session['name'] = user_login.name
        request.session['user_id'] = user_login.id
        messages.success(request, "You've successfully logged in")
        return redirect('/homepage')
    else:
        errors.append('Email/Password is incorrect')
        for error in errors:
            messages.warning(request, error)
        return redirect('/')


def homepage(request): 
    # try:
        user = User.objects.get(id=request.session['user_id'])
        
        all_users = User.objects.all()
        #print all_users
        other_users = User.objects.all().exclude(id=request.session['user_id'])
        #print other_users    
        
        #take whole object and filter on html 
        #make seperate context items to easily loop through items


        your_trips = Trip.objects.filter(user=user)
        other_trips = Trip.objects.exclude(user=user)
        context = {
            'user': user,
            'other_trips': other_trips,
            'your_trips': your_trips,        
        }    
        return render (request, "homepage.html", context)
    # except:
        
        # return redirect('/')

def create(request):
    

    return render(request, "addtrip.html")

def collect_data(request):
    errors = Trip.objects.validate_trip(request.POST)
    location = request.POST["location"]
    description = request.POST["description"]
    date_from = request.POST["date_from"]
    date_to = request.POST["date_to"]
    current_user = User.objects.get(id=request.session["user_id"])

    if len(errors):
        for error in errors:
            messages.warning(request, error)
        return redirect ('/create')
    else:

        Trip.objects.create(location=location, description=description, date_from=date_from, date_to=date_to, user=current_user)

        return redirect('/homepage')

def trip_profile(request, trip_id):

    current_trip = Trip.objects.get(id=trip_id)
    print current_trip
    other_users = current_trip.users.exclude(id=current_trip.user.id)
    print other_users
    context = {
        'trip': Trip.objects.get(id=trip_id),
        'other_users': other_users,
    }
    return render(request, "profile.html", context)

def join_trip(request, trip_id):
    current_user = User.objects.get(id=request.session['user_id'])
    current_trip = Trip.objects.get(id=trip_id)
    current_trip.users.add(current_user)
    current_trip.save()
    # give confirmation of joining trip
    messages.success(request, "Pack your bags!!!")

    return redirect('/homepage')


def logout(request):
    request.session.clear()
    return redirect('/')

Django/sunday_test_project/apps/sunday_test/templates/addtrip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add trip page</title>
</head>
<body>
        <a href= "{% url 'sunday_test_project:logout' %}">Logout</a>
        <a href= "{% url 'sunday_test_project:homepage' %}">homepage</a>
    <h1>ADD A TRIP!</h1>
    <div>
            {% if messages %}
            <ul> 
                {% for message in messages %}                
                   <li> {{ message }} </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    <div>
        <form action= "{% url 'sunday_test_project:collect_data' %}" method="POST">
                {% csrf_token %}
                location:<br>
                
                <input type="text" name="location" >
                <br>
                description:<br>
                <input type="text" name="description" >
                <br>
                travel date from:<br>
                <input type="date" name="date_from">
                <br>             
                travel date to:<br>
                <input type="date" name="date_to" >
                <br>                
                <input type="submit" value="add">
            </form> 
    </div>
</body>
</html>

Django/sunday_test_project/apps/sunday_test/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>material things</title>
</head>
<body>
        <h1>Success, Welcome {{user.name}}</h1>


        

        <div>
                {% if messages %}
                <ul> 
                    {% for message in messages %}                
                       <li> {{ message }} </li>
                    {% endfor %}
                </ul>
                {% endif %}
        </div>
        
        
        <div class="logout">
            <form action="logout" method="POST">
                {% csrf_token %}
                <input type="submit" name="logout" value="logout">
            </form>
        </div>


    <div><h2>Your travel plans</h2>
        <table>
                <tr>
                    <th>Destination</th>
                    <th>Travel Start Date</th>
                    <th>Travel End Date</th>
                    <th>Plan</th>
                </tr>
                {% if your_trips %}
                {% for trip in your_trips %}            
                <tr>
                    <td><a href="{% url 'sunday_test_project:trip_profile' trip.id %}">{{trip.location}}</a></td>
                    <!-- <td>{{trip.location}}</td> -->
                    <td>{{trip.date_from}}</td>
                    <td>{{trip.date_to}}</td>
                    <td>{{trip.description}}</td>                                                 
                    
                    </tr>
                {% endfor %}
                {% else %}<p> You have no travel plans</p>
            {% endif %}            
        </table>   

    </div>

    <div><h2>Other users travel plans</h2>
        <table>
                <tr>
                    <th>Name</th>
                    <th>Destination</th>
                    <th>Travel Start Date</th>
                    <th>Travel End Date</th>
                    <th>Do you Want to Join?</th>
                </tr>
                {% if other_trips %}
                {% for trip in other_trips %}            
                <tr>
                    <td>{{trip.user.name}}</td>
                    <td><a href="{% url 'sunday_test_project:trip_profile' trip.id %}">{{trip.location}}</a></td>
                    <!-- <td>{{trip.location}}</td> -->
                    <td>{{trip.date_from}}</td>
                    <td>{{trip.date_to}}</td>
                    <td><a href="{% url 'sunday_test_project:join_trip' trip.id %}">Join?</a></td>                                                 
                    
                    </tr>
                {% endfor %}
                {% else %}<p> You have no travel plans</p>
            {% endif %}            
        </table>
    </div>
    
    <a href="{% url 'sunday_test_project:create' %}">add new trip</a>
</body>
</html>

Django/sunday_test_project/apps/sunday_test/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Gifts wanted list</title>
</head>
<body>
    <h1> Welcome! </h1>
    <h2>Registration</h2> 

    <!-- Warning messages if login/reg fails -->
    <div>
        {% if messages %}
        <ul class="messages"> 
            {% for message in messages %}
            
               <li> {{ message }} </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    <!--  -->
    
    <div>        
        <form action= "{% url 'sunday_test_project:register' %}" method="POST"> <!--format is as shown "<insert brace>% url 'users:logout' %<insert brace>"           big url : little url n due to namespace convention-->
            {% csrf_token %}
            name:<br>
            <!-- input means form -->
            <input type="text" name="name" > <!-- need? value=""-->
            <br>
            Username:<br>
            <input type="text" name="alias" >
            <br>
            email:<br>
            <input type="email" name="emailreg">
            <br>             
            Password:<br>
            <input type="password" name="password" >
            <br>
            <p>Password should be at least 8 characters</p>
            Password Confirm:<br>
            <input type="password" name="confirm" placeholder="Pass Confirm"><br>
            Date Hire:<br>
            <input type="date" name="bday" placeholder=" mm/dd/yyyy">
            <input type="submit" value="Register">
        </form>    
    </div>
    <h2>Login<h2>
    <div>       
        <form action="{% url 'sunday_test_project:login' %}" method="POST">
            {% csrf_token %} 

            <!-- Select one to comment out, either email or username -->
            <!-- email:<br>
            <input type="email" name="emaillog" >
            <br> -->
            username:<br>
            <input type="text" name="alias">
            <br>
            Password:<br>
            <input type="password" name="password">
            <br>            
            <input type="submit" value="Login">
        </form>
    </div>

</body>
</html>

Django/sunday_test_project/apps/sunday_test/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profile Page</title>
</head>
<body>
        <a href= "{% url 'sunday_test_project:logout' %}">Logout</a>
        <a href= "{% url 'sunday_test_project:homepage' %}">homepage</a>
        
        <div>
            <h1>{{trip.location}}</h1>
            <p>Planned By: {{trip.user.name}}</p>
            <p>Description: {{trip.description}}</p>
            <p>Travel Date From: {{trip.date_from}}</p>
            <p>Travel Date To: {{trip.date_to}}</p>
        </div>

        <div>
            <h1>Other users in your party</h1>
            {% for person in other_users %}
                <!-- % for name in person % -->
            <p>{{person.name}}</p>
                <!-- % endfor % -->
            {% endfor %}

        </div>

    
</body>
</html>