Django/travel/travel/apps/login_register/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register$', register, name='register'),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
]

Django/travel/travel/apps/travel/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^new$', new, name='new'),
    url(r'^create$', create, name='create'),
    url(r'^join/(?P<trip_id>\d+)$', join, name='join'),
    url(r'^cancel/(?P<trip_id>\d+)$', cancel, name='cancel'),
    url(r'^show/(?P<trip_id>\d+)$', show, name='show'),
    url(r'^delete/(?P<trip_id>\d+)$', delete, name='delete'),
]

Django/travel/travel/travelbuddy/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login_register.urls', namespace='users')),
    url(r'^travel/', include('apps.travel.urls', namespace='travel')),
]

Django/travel/travel/apps/travel/models.py
from __future__ import unicode_literals
from django.db import models
#.. here!
from ..login_register.models import User
from datetime import datetime

class TravelManager(models.Manager):
    def validate_travel(self, input, user):
        errors = []
        loc = input['destination']
        plan = input['plan']
        date_from = input['date_from']
        date_to = input['date_to']
        if not loc or loc.isspace():
            errors.append("Input:Destination")
        if not plan or plan.isspace():
            errors.append("input: plan")
        if not date_from:
            errors.append("select: travel date from")
        if not date_to:
            errors.append("select: travel date to")
        
        
        #-----for future dates------------------------------------------------
        if date_from and date_to:
            today = datetime.now().strftime('%Y-%m-%d')
        if date_from < today:
                errors.append("future notnow")
        if date_from > date_to:
                errors.append('dates dont match')
        
        if errors:
            return (False, errors)
        trip = self.create(destination=loc, plan=plan, date_from=date_from, date_to=date_to, user=user)
        trip.users.add(user)
        return (True, "trip added!")


class Travel(models.Model):
    destination = models.CharField(max_length=55)
    plan = models.TextField()
    date_from = models.DateField()
    date_to = models.DateField()
    #to connect-----------manymany and forign
    users = models.ManyToManyField(User, related_name='travels')
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TravelManager()
    def __repr__(self):
        return self.destination

    

Django/travel/travel/apps/travel/views.py
from django.shortcuts import render,  redirect
from ..login_register.models import User
from .models import Travel
from django.urls import reverse
from django.contrib import messages

def index(request):
    user = User.objects.get(id=request.session['user'])
    trips = Travel.objects.filter(users=user).order_by('date_from','date_to')
    trips_others = Travel.objects.exclude(users=user).order_by('date_from','date_to')
    context = {
        'user' : user,
        'trips' : trips,
        'others' : trips_others
    }
    return render(request, 'travel/index.html', context)

def new(request):
    return render(request, 'travel/new.html')

def create(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.session['user'])
        result = Travel.objects.validate_travel(request.POST, user)
        if result[0]:
            messages.success(request, result[1])
            return redirect(reverse('travel:index'))
        print_messages(request, result[1])
    return redirect(reverse('travel:new'))

def join(request, trip_id):
    Join = User.objects.get(id=request.session['user'])
    trip = Travel.objects.get(id=trip_id)
    trip.users.add(Join)
    messages.success(request, "Joined!")
    return redirect(reverse('travel:index'))

def cancel(request, trip_id):
    Cancel = User.objects.get(id=request.session['user'])
    trip = Travel.objects.get(id=trip_id)
    trip.users.remove(Cancel)
    messages.success(request, "cancelled!")
    return redirect(reverse('travel:index'))

def delete(request, trip_id):
    Travel.objects.get(id=trip_id).delete()
    messages.success(request, "deleted")
    return redirect(reverse('travel:index'))

def show(request, trip_id):
    trip = Travel.objects.get(id=trip_id)
    other_users = trip.users.exclude(id=trip.user.id).order_by('name')
    context = {
        'trip' : trip,
        'others' : other_users
    }
    return render(request, 'travel/show.html', context)

def print_messages(request, error_list):
     for error in error_list:
        messages.error(request, error)

Django/travel/travel/apps/travel/templates/travel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DOCUMENT</title>

</head>
<body>
    <a id="logout" href="{% url 'users:logout' %}">Logout</a>
    <h2>Welcome, {{ user.username|title }} !</h2>
    {% if messages %}
        {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
    <h3>trip schedule</h3>
    <table id="mytrip">
        <thead>
            <tr>
                <th>Destination</th>
                <th>start date</th>
                <th>end date</th>
                <th>plan</th>
            </tr>
        </thead>
        <tbody>
        {% for trip in trips %}
            <tr>
                <td>
                    <a  class="dest" href="{% url 'travel:show' trip.id %}">
                        {{ trip.destination }}</a>
                </td>
                <td>{{ trip.date_from}}</td>
                <td>{{ trip.date_to}}</td>
                <td>{{ trip.plan }}</td>
                {% if user == trip.user %}
                    <td>
                        <a id="del" href="{% url 'travel:delete' trip.id %}" onClick=deleteConfirm()>Erase?

                        </a>
                    </td>
                {% else %}
                    <td><a href="{% url 'travel:cancel' trip.id %}">Cancel</a></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h3>friends travels</h3>
    <table id="others">
        <thead>
            <tr>
                <th>Name</th>
                <th>location</th>
                <th>start date</th>
                <th>end date</th>
                <th>join them</th>
            </tr>
        </thead>
        <tbody>
        {% for trip in others %}
            <tr>
                <td>{{ trip.user.name|title }}</td>
                <td>
                    <a class="dest" href="{% url 'travel:show' trip.id %}">{{ trip.destination}}
                    </a>
                </td>
                <td>{{ trip.date_from}}</td>
                <td>{{ trip.date_to}}</td>
                <td><a href="{% url 'travel:join' trip.id %}">Join</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'travel:create' %}">add new trip</a>
</body>
</html>

Django/travel/travel/apps/travel/templates/travel/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>DOCUMENT</title>
    
</head>
<body>
    <a id="back" href="{% url 'travel:index' %}">Home</a>
    <a href="{% url 'users:logout' %}">Logout</a>
    <h2>Add a Trip</h2>
    <form action="{% url 'travel:create' %}" method="post">
        {% csrf_token %}
        <label>Destination</label>
        <input type="text" name="destination">
        <label>Description</label>
        <textarea name="plan"></textarea>
        <label>Travel Date From:</label>
		<input class="date" type='date' name='date_from'>
		<label>Travel Date To:</label>
		<input class="date" type='date' name='date_to'>
        <button type="submit">Add</button>
    </form>
    {% if messages %}
        {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
</body>
</html>

Django/travel/travel/apps/travel/templates/travel/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DOCUMENT</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    
</head>
<body>
    <a id="back" href="{% url 'travel:index' %}">Home</a>
    <a href="{% url 'users:logout' %}">Logout</a>
    <h2>{{ trip.destination }}</h2>
    <ul id="trip">
        <li>Planned By:</li><p>{{ trip.user.name}}</p>
        <li>Description:</li><p>{{ trip.plan }}</li>
        <li>Travel Date From:</li><p>{{ trip.date_from }}</p>
        <li>Travel Date To:</li><p>{{ trip.date_to  }}</p>
    </ul>
    <h3>Other Users' joining the trip:</h2>
    <ul id="other">
    {% for user in others %}
        <p>{{ user.name }}</p>
    {% endfor %}
    </ul>
</body>
</html>